name: Deploy hosting and functions on PR

on:
  pull_request:
    branches:
      - main

jobs:
  deploy_hosting_and_functions:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies (to deploy functions)
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm ci

      - name : Deploy functions
        run: npm run deploy:token ${{ secrets.GCLOUD_TOKEN }}
